config/routes.rb
Listy::Application.routes.draw do
  resources :list_items

  resources :lists

  devise_for :users

  root :to => "lists#index"

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :list_items
  accepts_nested_attributes_for :list_items, :allow_destroy => true
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  # GET /list_items
  # GET /list_items.xml
  def index
    @list_items = ListItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @list_items }
    end
  end

  # GET /list_items/1
  # GET /list_items/1.xml
  def show
    @list_item = ListItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list_item }
    end
  end

  # GET /list_items/new
  # GET /list_items/new.xml
  def new
    @list_item = ListItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list_item }
    end
  end

  # GET /list_items/1/edit
  def edit
    @list_item = ListItem.find(params[:id])
  end

  # POST /list_items
  # POST /list_items.xml
  def create
    @list_item = ListItem.new(params[:list_item])

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to(@list_item, :notice => 'List item was successfully created.') }
        format.xml  { render :xml => @list_item, :status => :created, :location => @list_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /list_items/1
  # PUT /list_items/1.xml
  def update
    @list_item = ListItem.find(params[:id])

    respond_to do |format|
      if @list_item.update_attributes(params[:list_item])
        format.html { redirect_to(@list_item, :notice => 'List item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @list_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.xml
  def destroy
    @list_item = ListItem.find(params[:id])
    @list_item.destroy

    respond_to do |format|
      format.html { redirect_to(list_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.xml
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.xml
  def show
    @list = List.find(params[:id], :include => :list_items)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.xml
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.xml
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to(@list, :notice => 'List was successfully created.') }
        format.xml  { render :xml => @list, :status => :created, :location => @list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.xml
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to(@list, :notice => 'List was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.xml
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to(lists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title aToAdo
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    %h1 aToAdo
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/list_items/_form.html.haml
= form_for @list_item do |f|
  -if @list_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list_item.errors.count, "error")} prohibited this list_item from being saved:"
      %ul
        - @list_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :finished
    = f.check_box :finished
  .actions
    = f.submit 'Save'

app/views/list_items/edit.html.haml
%h1 Editing list_item

= render 'form'

= link_to 'Show', @list_item
\|
= link_to 'Back', list_items_path

app/views/list_items/index.html.haml
%h1 Listing list_items

%table
  %tr
    %th Description
    %th Finished
    %th
    %th
    %th

  - @list_items.each do |list_item|
    %tr
      %td= list_item.description
      %td= list_item.finished
      %td= link_to 'Show', list_item
      %td= link_to 'Edit', edit_list_item_path(list_item)
      %td= link_to 'Destroy', list_item, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New List item', new_list_item_path

app/views/list_items/new.html.haml
%h1 New list_item

= render 'form'

= link_to 'Back', list_items_path

app/views/list_items/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @list_item.description
%p
  %b Finished:
  = @list_item.finished

= link_to 'Edit', edit_list_item_path(@list_item)
\|
= link_to 'Back', list_items_path

app/views/lists/_form.html.haml
= form_for @list do |f|
  -if @list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg
  = f.label :name, "Name:"
  = f.text_field :name
  %ul.list
    = f.fields_for :list_items do |item_fields|
      %li.item
        = item_fields.text_field :description
  .actions
    = f.submit 'Save'

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'



= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
%h1 Listing lists

%table
  %tr
    %th Name
    %th{ :colspan => 3 } Options

  - @lists.each do |list|
    %tr
      %td= list.name
      %td= link_to 'Show', list
      %td= link_to 'Edit', edit_list_path(list)
      %td= link_to 'Destroy', list, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New List', new_list_path

app/views/lists/new.html.haml
%h1 New list

= render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.haml
%h2= @list.name

- unless @list.list_items.empty?
  %ul.list
    - @list.list_items.each do |item|
      %li= item.description


= link_to 'Edit', edit_list_path(@list)
\|
= link_to 'Back', lists_path